/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as ObjectsHandleRouteImport } from './routes/objects.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsHandleRoute = ObjectsHandleRouteImport.update({
  id: '/objects/$handle',
  path: '/objects/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/objects/$handle': typeof ObjectsHandleRoute
  '/artists/': typeof ArtistsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/objects/$handle': typeof ObjectsHandleRoute
  '/artists': typeof ArtistsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/objects': typeof ObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/objects/$handle': typeof ObjectsHandleRoute
  '/artists/': typeof ArtistsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/objects/': typeof ObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ambassadors'
    | '/artists/$slug'
    | '/journal/$slug'
    | '/objects/$handle'
    | '/artists/'
    | '/journal/'
    | '/objects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ambassadors'
    | '/artists/$slug'
    | '/journal/$slug'
    | '/objects/$handle'
    | '/artists'
    | '/journal'
    | '/objects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ambassadors'
    | '/artists/$slug'
    | '/journal/$slug'
    | '/objects/$handle'
    | '/artists/'
    | '/journal/'
    | '/objects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ObjectsHandleRoute: typeof ObjectsHandleRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$handle': {
      id: '/objects/$handle'
      path: '/objects/$handle'
      fullPath: '/objects/$handle'
      preLoaderRoute: typeof ObjectsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  ObjectsHandleRoute: ObjectsHandleRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
